---
title: "R_fishSize"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set("~/Biology/146/finalProject_fishSize")

library(dplyr)
library(tidyverse)
library(ggplot2)
library(car)
```

## MPA Effect on Kelp Bass Size

### Reading in data and displaying first six lines

```{r}
fishData <- read.csv("Annual_fish_comb_20200108.csv")
head(fishData)
```

## Subsetting the data to only include kelp bass 

```{r, echo=TRUE}
## Subset data to only include kelp bass
bass1 <- subset(fishData, SP_CODE=="PCLA")

## Remove all -99999 from dataset
bass2 = bass1[-which(bass1$SIZE < 0),]

## Include only the columns of interest to simplify the dataset
bass3 = bass2[c("YEAR", "SITE", "SP_CODE", "SIZE", "COUNT")]

## Replicates the rows based on the values of the "COUNT" column
index <- rep(1:nrow(bass3), bass3$COUNT)
bass_size <- bass3[index, ]

```


```{r}
##Calculate the average size of the kelp bass at each YEAR and SITE
head(bass_size)
bass_avg = bass_size %>% group_by(YEAR, SITE, SP_CODE) %>% 
  summarize_at(vars(SIZE), funs(mean))

##Plot average size of kelp bass by site by year 
## The colors in each site give you a rough idea of the relative average size between sites in a given year 
ggplot(bass_avg, aes(x=YEAR, y=SIZE))+
  geom_col(aes(fill=SITE))+
  labs(y="Total size across all sites")+
  ggtitle("Average size of bass across sites and years")

```
```{r}
## Filter out all sites except MOHK, CARP (non MPAs) and IVEE and NAPLES (MPAs)
bass_comp = bass_avg[which(bass_avg$SITE %in% c("MOHK", "CARP", "IVEE", "NAPL")),]

##Make a column that outputs "CONTROL" if CARP or MOHK. Will output "MPA" if IVEE or NAPL. 
bass_comp$status <- ifelse(bass_comp$SITE == "MOHK" | bass_comp$SITE=="CARP", "CONTROL", "MPA")

##Group by MPA status and year. Get the mean of the two different states, by year 
bass_comp_avg = bass_comp %>% group_by(YEAR, status, SP_CODE) %>% 
  summarize_at(vars(SIZE), funs(mean))

##Make a grouped column chart that shows avg bass size for each year inside and outside of MPAs 
## *Note: MPA status starts in 2012. 
# ggplot(bass_comp_avg, aes(fill=status, x=YEAR, y=SIZE))+
#   geom_bar(position="stack", stat="identity")+
#   ggtitle("Average kelp bass size inside and outside MPAs")


##Box plot for sites
bass_size_post <- bass_size[which(bass_size$YEAR > 2011), ]
bass_size_post$status <- ifelse(bass_size_post$SITE == "NAPL" | bass_size_post$SITE=="IVEE", "MPA", "CONTROL")
bass_size_post <- bass_size_post[-which(bass_size_post$SITE=="SCDI" | bass_size_post$SITE=="SCTW"),]

ggplot(bass_size_post, aes(x=status, y=SIZE))+
  geom_boxplot()+
  ggtitle("MPA vs Control: Average kelp bass size")+
  theme(plot.title = element_text(hjust=0.5))

# str(bass_comp_avg)
##Subset the data further to only include post mpa years for inside/outside 
bass_comp_post <- bass_comp_avg[which(bass_comp_avg$YEAR > 2012), ]

# ## Remake the grouped column chart with the subsetted years 
ggplot(bass_comp_post, aes(x=YEAR, y=SIZE, fill=status))+
  geom_bar(position="dodge", stat="identity")+
  labs(y="Average size (cm)")+
  ggtitle("Average kelp bass size inside and outside of MPAs")

```



```{r}



 ##This is the averaged data analysis
bass_comp_ttest = bass_comp[which(bass_comp$SITE %in% c("IVEE", "NAPL")),]

#subsetting the data into Pre MPA and Post MPA
pre_mpa = bass_comp_ttest[which(bass_comp_ttest$YEAR %in% c("2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011")),]
post_mpa = bass_comp_ttest[which(bass_comp_ttest$YEAR %in% c("2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")),]

## Boxplot for pre and post average sizes
bass_comp_ttest$status <- ifelse(bass_comp_ttest$YEAR <2012, "PRE", "POST")
ggplot(bass_comp_ttest, aes(x=status, y=SIZE, fill=status))+
  geom_boxplot()

#Looking to see if the data is normal
shapiro.test(pre_mpa$SIZE)
qqPlot(pre_mpa$SIZE, main = "Pre MPA qqPlot", ylab = "Fish Size Data")
ggplot(pre_mpa, aes(x=SIZE)) + 
  geom_histogram(binwidth=4, color="black", fill="white")


shapiro.test(post_mpa$SIZE)
qqPlot(post_mpa$SIZE, main = "Post MPA qqPlot", ylab = "Fish Size Data")
ggplot(post_mpa, aes(x=SIZE)) + 
  geom_histogram(binwidth=3, color="black", fill="white")


#The data for Pre and Post MPA fall under the CI for normality for the qqplots
#The p values are not smaller than 0.05 for Pre or Post MPA data, we fail to reject that data is normal


#Because data appears to be normal an F-test is conducted to see if variances are equal
var.test(pre_mpa$SIZE, post_mpa$SIZE)
#The F test has a p-value greater than 0.05, we fail to reject that variances are equal


#A two-sample t-test is conducted assuming equal variance to compare the difference in means
t.test(pre_mpa$SIZE, post_mpa$SIZE, var.equal=TRUE)

#Null hypothesis: Size does not change between MPA statuses (the difference in means is 0).
#Alternative hypothesis: Size does change between MPA statuses (the difference in means is not 0)
#The p-value is greater than 0.05, we fail to reject that the difference in means is 0
#There is no significant difference in means for Pre and Post MPA kelp bass sizes  

```

```{r}
# #This is off of the raw data. Not sure which one we want to use (Sarah)

# ##Subset the raw data to only include the sites IVEE and NAPL
bass_size_ttest2 = bass_size[which(bass_size$SITE %in% c("IVEE", "NAPL")),]

## Subset the dataset again to include the pre_mpa years (2000-2011)
pre_mpa2 = bass_size_ttest2[which(bass_size_ttest2$YEAR %in% c("2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011")),]

## Subset the data to include only the post mpa years (2012-2019)
post_mpa2 = bass_size_ttest2[which(bass_size_ttest2$YEAR %in% c("2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")),]

## Test if the pre_mpa sizes are normally distributed
shapiro.test(pre_mpa2$SIZE)
qqPlot(pre_mpa2$SIZE, main = "Pre MPA qqPlot", ylab = "Fish Size Data")
ggplot(pre_mpa2, aes(x=SIZE)) + geom_histogram()

## Test if the pos_mpa sizes are normally distributed
shapiro.test(post_mpa2$SIZE)
qqPlot(post_mpa2$SIZE, main = "Post MPA qqPlot", ylab = "Fish Size Data")
ggplot(post_mpa2, aes(x=SIZE)) + geom_histogram()


#Since the data is NOT normally distributed we want to use a LEVENE test (instead of an F test) to test if the variances are equal.
## First, we wrangle the data and create a "status" column in the dataset for pre/post mpa
bass_size_ttest2$status <- ifelse(bass_size_ttest2$YEAR <2012, "PRE", "POST")

## Boxplot for pre and post average sizes
ggplot(bass_size_ttest2, aes(x=status, y=SIZE, fill=status))+
  geom_boxplot()

## Then we do the levene test, which compares the size of the bass against the two conditions in the status column
leveneTest(bass_size_ttest2$SIZE, bass_size_ttest2$status)

## Since the variances are not equal we do a Welch's t test
t.test(pre_mpa2$SIZE, post_mpa2$SIZE, var.equal=FALSE)

## There appears to be a significant difference! (p value less than 0.05)
# We reject the null hypothesis that there is no difference in mean size of kelp bass pre/post mpa

## BUT. The average size of the kelp bass DECREASED after MPAs were established. This makes it appear that MPA status might decrease the average size of the kelp bass. This is interesting...



```

#ADDITIONAL ANALYSIS

```{r}
# Null hypothesis: There is no difference in the average number of kelp bass over 30 cm before and afer MPA zones were established in sites IVEE and NAPL. 
# Alt: There IS a difference in the average number of kelp bass over 30 cm before and after MPA zones were established. 


#Create a column that identifies kelp bass as juveniles (smaller than 30 cm) and adults (over 30 cm)
bass_size_ttest2$age <- ifelse(bass_size_ttest2$SIZE < 30, "juvenile", "adult")

## Subset the data to only include adults in the dataset 
bass_size_adult <- subset(bass_size_ttest2, bass_size_ttest2$age=="adult")

## Visualize the data using a histogram to check distribution of data 
ggplot(bass_size_adult, aes(x=SIZE))+
  geom_histogram(binwidth = 2, color="black", fill="white")+
  labs(x="Size (cm)")+
  ggtitle("Size distribution of adult kelp bass inside MPAs")

## Size distribution is heavily right skewed. However, since we only want the NUMBER of adults, the size distribution is irrelevant. 
bass_adult_count = bass_size_adult %>% group_by(YEAR, status, SP_CODE) %>% 
  summarize_at(vars(COUNT), funs(length))

## Lets visualize this data using a histogram 
ggplot(bass_adult_count, aes(x=COUNT))+
  geom_histogram(binwidth = 5, color="black", fill="white")+
  labs(x="Number of adult kelp bass")+
  ggtitle("Distribution of the number of adult kelp bass")

## Heavily right skewed. Perform a log transformation on count 
bass_adult_count$logCount <- log(bass_adult_count$COUNT)

## check normality 
ggplot(bass_adult_count, aes(x=logCount))+
  geom_histogram(binwidth = .6, color="black", fill="white")+
  labs(x="Number of ln(adult kelp bass)")+
  ggtitle("Distribution of the ln(number of adult kelp bass)")

qqPlot(bass_adult_count$logCount)
shapiro.test(bass_adult_count$logCount)

## Split the data into pre/post mpa treatments
PRE_bass_adult_count <- subset(bass_adult_count, bass_adult_count$status=="PRE")
POST_bass_adult_count <- subset(bass_adult_count, bass_adult_count$status=="POST")

## Data is normal, so I'm using an F test!
var.test(PRE_bass_adult_count$logCount, POST_bass_adult_count$logCount)

## variances are equal. Moving forward with a standard t test 
t.test(PRE_bass_adult_count$logCount, POST_bass_adult_count$logCount)

exp(1)^1.718
exp(1)^2.637

## Based on the results of the t test there IS a difference in the number of adults before and after the creation of the MPA. The number of adults increases from an average of 5.5 to an average of 14. 
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
